'use client'
import { ApolloClient, ApolloProvider, InMemoryCache } from "@apollo/client";
import { ThemeProvider } from "@mui/material";
import { SnackbarProvider } from "notistack";
import React, { useEffect } from "react";
import { theme } from "../common/theme";
import { AuthProvider } from "../context/auth-context";
import MasterLayout from "../layout";
import './globals.css';
import { RecoilRoot } from "recoil";
import { usePathname, useRouter } from "next/navigation";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export const client = new ApolloClient({
  uri: 'http://localhost:8081/graphql',
  cache: new InMemoryCache(),
});

type Props = {
  children: React.ReactNode
}

const RootLayout = ({ children }: Props) => {
  const path = usePathname()

  return (
    <html lang="en" className={path !== '/login' ? 'overflow-y-scroll' : 'overflow-y-auto'}>
      <body>
        <RecoilRoot>
          <ThemeProvider theme={theme}>
            <ApolloProvider client={client}>
              <AuthProvider>
                <SnackbarProvider>
                  <MasterLayout />
                  {children}
                </SnackbarProvider>
              </AuthProvider>
            </ApolloProvider>
          </ThemeProvider>
        </RecoilRoot>
      </body>
    </html>
  )
}
export default RootLayout
